# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#   - '@naturalcycles/*'
#   - vitest
#   - '@vitest/*'

blockExoticSubdeps: true
ignorePatchFailures: false

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - oxlint
  - oxlint-tsgolint
  - oxfmt
