ignorePatchFailures: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@naturalcycles/*'
  - vitest
  - '@vitest/*'
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - eslint
  - oxlint
  - prettier
  - '@biomejs/biome'
